{% set name = "meilisearch" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/meilisearch/meilisearch/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5a7a5dd79e772ca1308afd8d92dcd3b5e546906fe01d30978783589133a78b77

build:
  skip: true  # [ppc64le]
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    # for the jemalloc-sys crate
    - {{ compiler('c') }}    # [linux or osx]
    - make                   # [linux]
test:
  commands:
    - meilisearch --help
    - meilisearch --version
    - meilitool --help
    - meilitool --version

about:
  home: https://www.meilisearch.com/
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Powerful, fast, and an easy to use search engine
  dev_url: https://github.com/meilisearch

extra:
  recipe-maintainers:
    - wolfv
