{% set name = "meilisearch" %}
{% set version = "0.2022.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/meilisearch/meilisearch/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 203fbbb99f544669691e1ddd61fedc4d99636776d1d80b60d155bcebfc9aaf98

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    # for the jemalloc-sys crate
    - {{ compiler('c') }}    # [linux]
    - make                   # [linux]
test:
  commands:
    - meilisearch --help
    - meilisearch --version

about:
  home: https://www.meilisearch.com/
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Powerful, fast, and an easy to use search engine
  dev_url: https://github.com/meilisearch

extra:
  recipe-maintainers:
    - wolfv
