{% set name = "meilisearch" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/meilisearch/meilisearch/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 59511c16ce76dd497d9d5b56250edef83e0e380a0f3175d84b612041db019be8

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    # for the jemalloc-sys crate
    - {{ compiler('c') }}    # [linux]
    - make                   # [linux]
test:
  commands:
    - meilisearch --help
    - meilisearch --version

about:
  home: https://www.meilisearch.com/
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Powerful, fast, and an easy to use search engine
  dev_url: https://github.com/meilisearch

extra:
  recipe-maintainers:
    - wolfv
