{% set name = "meilisearch" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/meilisearch/meilisearch/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 82209896c9aae0d75441efeb1ac477c245033bce859d96af3bf740c7c0d8b012

build:
  skip: True  # [ppc64le]
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    # for the jemalloc-sys crate
    - {{ compiler('c') }}    # [linux or osx]
    - make                   # [linux]
test:
  commands:
    - meilisearch --help
    - meilisearch --version
    - meilitool --help
    - meilitool --version

about:
  home: https://www.meilisearch.com/
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Powerful, fast, and an easy to use search engine
  dev_url: https://github.com/meilisearch

extra:
  recipe-maintainers:
    - wolfv
